# Generated by Django 4.1.7 on 2023-02-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(max_length=300)),
                ('type', models.CharField(choices=[('estate', 'estate_type'), ('rent', 'rent')], max_length=300)),
                ('upload_files', models.FileField(upload_to='')),
            ],
        ),
    ]
