# Generated by Django 4.1.7 on 2023-02-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_rename_upload_files_room_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rent',
            field=models.FloatField(),
        ),
    ]
