# Generated by Django 4.1.7 on 2023-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_remove_room_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('estate', 'estate'), ('rent', 'rent')], max_length=300),
        ),
    ]
