# Generated by Django 4.1.7 on 2023-02-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_room_rent_alter_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Estate', 'Estate'), ('Rent', 'Rent')], max_length=300),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_email', models.CharField(max_length=30)),
                ('customer_location', models.CharField(max_length=300)),
                ('booking_days', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
