# Generated by Django 4.1.7 on 2023-02-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_alter_room_type_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=5, null=True),
        ),
    ]
