# Generated by Django 4.1.7 on 2023-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_alter_customer_booking_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=30)),
                ('agent_email', models.EmailField(max_length=254)),
                ('agent_cell', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='room_type',
        ),
        migrations.AlterField(
            model_name='customer',
            name='booking_days',
            field=models.DateTimeField(),
        ),
    ]
