# Generated by Django 4.1.5 on 2023-01-23 17:09

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('rooms', models.IntegerField(default=1)),
                ('bedrooms', models.IntegerField(default=1)),
                ('rent', models.FloatField()),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('surrounding_surburb', models.CharField(max_length=30)),
                ('has_garage', models.BooleanField(default=False)),
                ('area', models.FloatField()),
            ],
        ),
    ]
