# Generated by Django 4.1.3 on 2023-02-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_alter_room_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.ImageField(default=None, max_length=8000, upload_to=''),
        ),
    ]
