# Generated by Django 4.1.3 on 2023-02-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_alter_room_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='images',
            new_name='image',
        ),
    ]
