# Generated by Django 4.1.3 on 2023-02-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_rename_images_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.CharField(default=None, max_length=8000),
        ),
    ]
