# Generated by Django 4.1.3 on 2023-02-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_alter_room_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='categories',
        ),
    ]
