# Generated by Django 4.1.5 on 2023-02-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_remove_room_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300)),
            ],
        ),
    ]
