# Generated by Django 4.1.5 on 2023-02-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0014_searchform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchForm',
            new_name='SearchModel',
        ),
    ]
